// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SunBloom.Modules.Catalog.Infrastructure;

#nullable disable

namespace SunBloom.Modules.Catalog.Infrastructure.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    partial class CatalogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SunBloom.Modules.Catalog.Domain.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentSkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_skill_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_skills");

                    b.HasIndex("ParentSkillId")
                        .HasDatabaseName("ix_skills_parent_skill_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_skills_slug");

                    b.ToTable("skills", "catalog");
                });

            modelBuilder.Entity("SunBloom.Modules.Catalog.Domain.SkillRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("FromSkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_skill_id");

                    b.Property<decimal>("Strength")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3, 2)
                        .HasColumnType("numeric(3,2)")
                        .HasDefaultValue(1.0m)
                        .HasColumnName("strength");

                    b.Property<Guid>("ToSkillId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_skill_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_skill_relationships");

                    b.HasIndex("FromSkillId", "Type")
                        .HasDatabaseName("ix_skill_relationships_from_skill_id_type");

                    b.HasIndex("ToSkillId", "Type")
                        .HasDatabaseName("ix_skill_relationships_to_skill_id_type");

                    b.HasIndex("FromSkillId", "ToSkillId", "Type")
                        .IsUnique()
                        .HasDatabaseName("uq_skill_rel");

                    b.ToTable("skill_relationships", "catalog", t =>
                        {
                            t.HasCheckConstraint("ck_skill_rel_no_self", "from_skill_id <> to_skill_id");
                        });
                });

            modelBuilder.Entity("SunBloom.Modules.Catalog.Domain.Skill", b =>
                {
                    b.HasOne("SunBloom.Modules.Catalog.Domain.Skill", null)
                        .WithMany()
                        .HasForeignKey("ParentSkillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_skills_skills_parent_skill_id");

                    b.OwnsOne("SunBloom.Modules.Catalog.Domain.ContentProvenance", "Provenance", b1 =>
                        {
                            b1.Property<Guid>("SkillId")
                                .HasColumnType("uuid")
                                .HasColumnName("id");

                            b1.Property<DateTimeOffset?>("GeneratedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("generated_at");

                            b1.Property<string>("GenerationSource")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("generation_source");

                            b1.Property<string>("GeneratorModel")
                                .HasMaxLength(100)
                                .HasColumnType("character varying(100)")
                                .HasColumnName("generator_model");

                            b1.Property<string>("GeneratorPromptVersion")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)")
                                .HasColumnName("generator_prompt_version");

                            b1.Property<string>("ReviewNotes")
                                .HasMaxLength(2000)
                                .HasColumnType("character varying(2000)")
                                .HasColumnName("review_notes");

                            b1.Property<string>("ReviewState")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("review_state");

                            b1.Property<DateTimeOffset?>("ReviewedAt")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("reviewed_at");

                            b1.Property<Guid?>("ReviewedByUserId")
                                .HasColumnType("uuid")
                                .HasColumnName("reviewed_by_user_id");

                            b1.HasKey("SkillId");

                            b1.HasIndex("ReviewState")
                                .HasDatabaseName("ix_skills_review_state");

                            b1.ToTable("skills", "catalog");

                            b1.WithOwner()
                                .HasForeignKey("SkillId")
                                .HasConstraintName("fk_skills_skills_id");
                        });

                    b.Navigation("Provenance")
                        .IsRequired();
                });

            modelBuilder.Entity("SunBloom.Modules.Catalog.Domain.SkillRelationship", b =>
                {
                    b.HasOne("SunBloom.Modules.Catalog.Domain.Skill", null)
                        .WithMany()
                        .HasForeignKey("FromSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_relationships_skills_from_skill_id");

                    b.HasOne("SunBloom.Modules.Catalog.Domain.Skill", null)
                        .WithMany()
                        .HasForeignKey("ToSkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_skill_relationships_skills_to_skill_id");
                });
#pragma warning restore 612, 618
        }
    }
}
